### ISSUE TITLE
I had to set the service endpoint to get the example to work...

### ISSUE THREAD

**Issue by ericdcobb** [balsamiq/hello-world-glisten#1]
Thanks for this! I was really confused on how to get glisten/swf working and this example was very helpful.

One small thing, I had to set the service endpoint to get the example to work (we are using the northern california region, maybe there is a default region?)

```groovy
service.setEndpoint("https://swf.us-west-1.amazonaws.com")
```

**Comment by kaaloo** [comment]
Hi, thanks!  Yes there is a default region which is us-east-1 so you did the right thing!
